import type { FastifyInstance } from "fastify";
import { intakeRoutes } from "./intake.js";
import { pipelineRoutes } from "./pipeline.js";
import { agentsRoutes } from "./agents.js";
import { programRoutes } from "./programs.js";
import { checkinRoutes } from "./checkins.js";
import { trainingRoutes } from "./training.js";
import { complianceRoutes } from "./compliance.js";
import { healthRoutes } from "./health.js";
import { adminRoutes } from "./admin.js";
import { redFlagRoutes } from "./red-flags.js";
import { dashboardRoutes } from "./dashboard.js";
import { chartRoutes } from "./charts.js";
import { mealPlanRoutes } from "./meal-plan.js";
import { recipeRoutes } from "./recipes.js";
import { shoppingRoutes } from "./shopping.js";
import { milestoneRoutes } from "./milestones.js";
import { scheduleRoutes } from "./schedule.js";
import { adjustmentRoutes } from "./adjustments.js";
import { insightRoutes } from "./insights.js";
import { techniqueRoutes } from "./techniques.js";
import { pantryRoutes } from "./pantry.js";

export async function registerRoutes(app: FastifyInstance) {
  await app.register(intakeRoutes);
  await app.register(pipelineRoutes);
  await app.register(agentsRoutes);
  await app.register(programRoutes);
  await app.register(checkinRoutes);
  await app.register(trainingRoutes);
  await app.register(complianceRoutes);
  await app.register(healthRoutes);
  await app.register(adminRoutes);
  await app.register(redFlagRoutes);
  await app.register(dashboardRoutes);
  await app.register(chartRoutes);
  await app.register(mealPlanRoutes);
  await app.register(recipeRoutes);
  await app.register(shoppingRoutes);
  await app.register(milestoneRoutes);
  await app.register(scheduleRoutes);
  await app.register(adjustmentRoutes);
  await app.register(insightRoutes);
  await app.register(techniqueRoutes);
  await app.register(pantryRoutes);
}
